config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new
  get 'tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  # def create
  # end


  # def edit
  # end

  # def update
  # end

  # def destroy
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<%@tasks.each do |task|%>
<h2><%=link_to task.title, task_path(task) %></h2>
<% end %>

<p><%= link_to "Create a task", new_path %></p>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<form action="/tasks" method=post>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Title</label>
  <input type="text" name="task[title]">
  <label for="details">Details</label>
  <input type="text" name="task[details]">
  <input type="submit">
</form>

app/views/tasks/show.html.erb
<h2><%=@task.title %></h2>
<p><%=@task.details %></p>
</ul>

<p><%= link_to "Go back to task list", tasks_path %></p>